{{- if .Values.cnpg.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cnpg.cluster.superuserSecret }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
type: Opaque
data:
  username: {{ "postgres" | b64enc }}
  password: {{ randAlphaNum 16 | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cnpg.cluster.appSecret }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
    cnpg.io/reload: "true"
type: Opaque
data:
  username: {{ "mealie" | b64enc }}
  password: {{ randAlphaNum 16 | b64enc }}
{{- end }}